maintainer       "Dell, Inc."
maintainer_email "crowbar@dell.com"
license          "Apache 2.0"
description      "Provides a library of useful barclamp stuff."
long_description "Provides helper functions for barclamp functions in Chef."
version          "0.9.5"
